Docker 2
Otus-DevOps-2022-02/dmitriy-re_microservices pull request #1
Opened 2022-05-22 16:38 UTC by dmitriy-re

2022-05-23 09:27 UTC, mrgreyves reviewed
Здравствуйте!)
Приложение у вас работает корректно?
Можете прислать скриншот?

2022-05-23 18:36 UTC, dmitriy-re commented
Проблема по второму заданию из д.з. docker-2 , не смог с помощью docker-machine (на linux) управлять контейнером на ВМ в yc , контейнер запускается, но не удается подключится к контейнеру по ssh. Зашел на ВМ в yc по ssh и там пытаюсь с помощью yml файлов из д.з. запустить контейнер. Но контейнер сразу же перестает работать. docker ps его не показывает.

2022-05-23 20:16 UTC, dmitriy-re commented
С помощью docker-machine удалось запустить контейнер, но он останавливается и не работает

2022-05-24 10:04 UTC, mrgreyves commented
Здравствуйте!)
В логах контейнера видно что нибудь?
Вполне возможно что проблема где то там =)

2022-05-26 08:42 UTC, mrgreyves requested changes
Отправлю в доработку
Что бы не мешалось в списке

2022-06-01 19:05 UTC, dmitriy-re commented
Прошу прощения, что долго не отвечал.
Вот лог
sudo docker logs -f reddit01
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
Puma starting in single mode...
* Puma version: 5.6.4 (ruby 2.5.1-p57) ("Birdie's Version")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 33
/reddit/helpers.rb:4: warning: redefining `object_id' may cause serious problems
! Unable to load application: NameError: uninitialized constant Mongo::Client
/reddit/app.rb:11:in `block in <top (required)>': uninitialized constant Mongo::Client (NameError)
	from /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1427:in `configure'
	from /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1919:in `block (2 levels) in delegate'
	from /reddit/app.rb:10:in `<top (required)>'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from config.ru:1:in `block in <main>'
	from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/configuration.rb:348:in `load_rackup'
	from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/configuration.rb:270:in `app'
	from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/runner.rb:150:in `load_and_bind'
	from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/single.rb:44:in `run'
	from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/launcher.rb:182:in `run'
	from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/cli.rb:81:in `run'
	from /var/lib/gems/2.5.0/gems/puma-5.6.4/bin/puma:10:in `<top (required)>'
	from /usr/local/bin/puma:23:in `load'
	from /usr/local/bin/puma:23:in `<main>'

2022-06-01 19:34 UTC, dmitriy-re commented
Как я понимаю проблема в reddit
NameError: uninitialized constant Mongo::Client /reddit/app.rb:11:in block in <top (required)>': uninitialized constant Mongo::Client (NameError)

Не заданна константа Mongo::Client  ,
но как это поправить не знаю

2022-06-01 19:47 UTC, dmitriy-re commented
Я не программист, но думаю здесь
db = Mongo::Client.new([ ENV['DATABASE_URL'] || '127.0.0.1:27017' ], database: 'user_posts', heartbeat_frequency: 2)
не описана

2022-06-02 14:08 UTC, mrgreyves commented
Оставил вам комментрий к файлу
Попробуйте поправить =)

2022-06-02 18:21 UTC, dmitriy-re commented
Не понял к какому файлу коммент? И где этот комментарий можно посмотреть?

2022-06-05 13:52 UTC, mrgreyves requested changes
<img width="911" alt="image" src="https://user-images.githubusercontent.com/34331259/172053964-b7debca0-7e9e-4f88-a79d-bc16ebcad642.png">

2022-06-05 13:52 UTC, mrgreyves commented on docker-monolith/mongod.conf
> +# Where and how to store data.
Кажется проблема в конфиге самой монги
Если быть точным то поехало форматирование файла

2022-06-15 19:26 UTC, dmitriy-re commented
Я этот конфиг и раньше поправил, сейчас загрузил в git
Ошибка та же
sudo docker logs reddit
about to fork child process, waiting until server is ready for connections.
forked process: 9
child process started successfully, parent exiting
Puma starting in single mode...
* Puma version: 5.6.4 (ruby 2.5.1-p57) ("Birdie's Version")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 32
/reddit/helpers.rb:4: warning: redefining `object_id' may cause serious problems
! Unable to load application: NameError: uninitialized constant Mongo::Client
/reddit/app.rb:11:in `block in <top (required)>': uninitialized constant Mongo::Client (NameError)
	from /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1427:in `configure'
	from /var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1919:in `block (2 levels) in delegate'
	from /reddit/app.rb:10:in `<top (required)>'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from config.ru:1:in `block in <main>'
	from /var/lib/gems/2.5.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `eval'
	from /var/lib/gems/2.5.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `new_from_string'
	from /var/lib/gems/2.5.0/gems/rack-2.2.3.1/lib/rack/builder.rb:105:in `load_file'
	from /var/lib/gems/2.5.0/gems/rack-2.2.3.1/lib/rack/builder.rb:66:in `parse_file'
	from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/configuration.rb:348:in `load_rackup'
	from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/configuration.rb:270:in `app'
	from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/runner.rb:150:in `load_and_bind'
	from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/single.rb:44:in `run'
	from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/launcher.rb:182:in `run'
	from /var/lib/gems/2.5.0/gems/puma-5.6.4/lib/puma/cli.rb:81:in `run'
	from /var/lib/gems/2.5.0/gems/puma-5.6.4/bin/puma:10:in `<top (required)>'
	from /usr/local/bin/puma:23:in `load'
	from /usr/local/bin/puma:23:in `<main>'

2022-06-15 19:44 UTC, dmitriy-re commented
cat mongod.conf 
# Where and how to store data.
storage:
  dbPath: /var/lib/mongodb
  journal:
    enabled: true
# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log
# network interfaces
net:
  port: 27017
  bindIp: 127.0.0.1

2022-06-15 20:20 UTC, dmitriy-re commented
mrgreyves , ошибка в Dockerfile . Ну так составлять д.з. , чтобы больше помучить это не про обучение.

2022-06-16 13:59 UTC, mrgreyves commented
Здравствуйте!)
А про что это?)
Дополнительный опыт дебагинга это всегда полезно

2022-06-16 14:00 UTC, mrgreyves approved these changes
Апрув ^_^

2022-06-16 18:17 UTC, merged